[change] Add pytest to runtests.py for sample_connection tests

diff --git a/runtests b/runtests
--- a/runtests
+++ b/runtests
@@ -1,17 +1,18 @@
 #!/bin/bash
-set -e
+set -ex
 
 echo "Starting standard tests"
-coverage run runtests.py --parallel --exclude-tag=selenium_tests \
-  || coverage run ./runtests.py --exclude-tag=selenium_tests
+# we currently --exclude-pytest because there is no pytest*.py test, and this is a pytest fail
+coverage run runtests.py --parallel --exclude-tag=selenium_tests --exclude-pytest \
+  || coverage run ./runtests.py --exclude-tag=selenium_tests --exclude-pytest
 
 echo "Starting selenium browser tests"
-./runtests.py --tag=selenium_tests --exclude-tag=channels --no-input
+./runtests.py --tag=selenium_tests --exclude-tag=channels --no-input --exclude-pytest
 
 echo "Starting selenium browser + channels live server tests (flaky due to segmentation faults)"
 for i in 1 2 3; do
   echo "Attempt $i/3"
-  ./runtests.py --tag=channels --no-input --failfast && break
+  ./runtests.py --tag=channels --no-input --failfast --exclude-pytest && break
 done
 
 echo "Starting tests for extensibility"
